### ISSUE TITLE
Please upload tarball with release

### ISSUE THREAD

**Issue by krytarowski** [ooxi/violetland#129]
I cannot get sanely the version 0.5 and package for NetBSD (via pkgsrc). The tag is without external modules.

**Comment by ooxi** [comment]
Would [this archive](https://github.com/ooxi/violetland/files/385684/violetland-0.5.tar.gz) fulfil your needs? If so it will be officially published.

**Comment by krytarowski** [comment]
Yes! It works and builds for NetBSD

**Comment by ooxi** [comment]
I have published [the source with external dependencies](https://github.com/ooxi/violetland/releases/download/0.5/violetland-source-with-dependencies.tar.gz) for version 0.5

Thanks for bringing Violetland to NetBSD! Are there any patches we could integrate upstream so you don't have to carry them around?

**Comment by coypoop** [comment]
Hi,
Could you make the tarball filename contain the version number?
Thanks

**Comment by ooxi** [comment]
While the file name itself does not contain the version number, the URL does. Is having the version number in the file name a requirement of `pgksrc`?

**Comment by coypoop** [comment]
It can be worked around, but we strongly prefer having the version in the filename.
Sorry for the extra trouble, and thanks for violetland!

**Comment by krytarowski** [comment]
We prefer versioned distfiles, as we are storing them on mirrors and it's more tricky to distinguish several versions of the same software but with different name.

**Comment by krytarowski** [comment]
After the decision of a change or not, I will import violetland into pkgsrc.

**Comment by ooxi** [comment]
Thanks for the input! I renamed the release :)
