### ISSUE TITLE
Fix website's download link

### ISSUE THREAD

**Issue by tukkek** [ooxi/violetland#142]
The current "Downloads" link on [Violetland's website](http://violetland.github.io/) points to [this page](https://github.com/ooxi/violetland/downloads), which seems to be outdated by GitHub itself. I can see [the releases page](https://github.com/ooxi/violetland/releases) actually offers a 0.5 download, while the former doesn't, so this should probably be the destination for the link instead.

**Comment by ooxi** [comment]
Thanks for the reminder! I fixed the download link in commit [eb196b100c9a8f4c1081587db87be02e0d2412d4](https://github.com/violetland/violetland.github.com/commit/eb196b100c9a8f4c1081587db87be02e0d2412d4) :-)
