### ISSUE TITLE
Tags for past releases

### ISSUE THREAD

**Issue by AMDmi3** [ooxi/violetland#70]
Could we have tags for past releases, at least for the latest one (0.4.3 if I'm not mistaken)?

**Comment by ooxi** [comment]
Thats a good idea. I'm not sure I find the old commits (maybe you can help?) but at least the current one is easy identifyable

**Comment by AMDmi3** [comment]
Done. I've run diff comparison of source tree against tarball and svn tag contents and added git tags for matching commits, see my fork. There were minor problems with some versions, where tarball and svn tag contents mismatched - I've given priority to tarball contents in these cases (0.4.3 and 0.4.0) as they included fixes and changelog updates missing in tags.

**Comment by ooxi** [comment]
Thanks very much! I've merged all your tags. Since I don't know how to attribute ownership of tags I've added a [CONTRIBUTORS.md](https://github.com/ooxi/violetland/blob/1db516ae554eced70153abdaf14e5303f833b7f2/CONTRIBUTORS.md) file :)

**Comment by AMDmi3** [comment]
Thanks, but that was not really necessary :)
